### ISSUE TITLE
iOS 11 Support

### ISSUE THREAD

**Issue by arsenal942** [kapetan/cordova-plugin-android-wifi-manager#1]
@kapetan I was just wondering if you ever planned on expanding into support for iOS 11? Apple recently added back the ability to connect to Wifi networks and I know you'd make a whole lot of developers cry from happiness (including myself) if we no longer had to generate stupid .mobiconfig XML documents.

**Comment by kapetan** [comment]
No, I don't have plans on supporting iOS. Sorry to disappoint. Android is also part of the name :)

**Comment by arsenal942** [comment]
I know it's apart of the name but a man can hope and dream. :(

**Comment by t2wu** [comment]
@arsenal942 
https://github.com/hoerresb/WifiWizard
