### ISSUE TITLE
getScanResults not working

### ISSUE THREAD

**Issue by mknnaren** [kapetan/cordova-plugin-android-wifi-manager#2]
getScanResults api is giving an empty array even after a successful onscanresultsavailable function.

**Comment by mknnaren** [comment]
I had connected the cordova app to the system and ran through the chrome dev tools to check on this.
Attaching the screenshot of empty array being returned by the getScanResults method.

![oie_g6kuzqgkcapc](https://user-images.githubusercontent.com/2345361/35044919-126bdcd0-fbb8-11e7-85c5-01981b016637.png)

**Comment by kapetan** [comment]
Did you give the app coarse location permission? It is required for `getScanResults` to work. The plugin will ask you to give location permission first time you try to use `getScanResults`.

**Comment by mknnaren** [comment]
Yeah, I gave the access to location permission when the prompt appeared.

**Comment by mknnaren** [comment]
**onscanresultsavailable** event is working fine and the event is being called on every refresh of wifi list. but the **getScanResults** function is returning an empty array. 
Do I need to give the coarse location permission manually in android native code?

**Comment by kapetan** [comment]
Accepting the prompt should be enough. I'm not sure why you're not getting any results.

**Comment by mknnaren** [comment]
UserAgent details of the phone I am using to test.

"Mozilla/5.0 (Linux; Android 6.0.1; Lenovo K53a48 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36"

**Comment by mknnaren** [comment]
Hey Kapetan,
Its working now after enabling the GPS.
In order to get WiFi scan results on Marshmallow and later, your app will need to request the ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission, and the **Location Mode setting must be enabled as well**.

Reference:
https://stackoverflow.com/questions/44835962/old-app-cant-get-wifi-scan-results-on-android-n

Thank you,
Naren

**Comment by kapetan** [comment]
Okay, didn't know that. Nice you figured it out.
