### ISSUE TITLE
Unable to add wifi configuration

### ISSUE THREAD

**Issue by timonsku** [kapetan/cordova-plugin-android-wifi-manager#5]
I always get back a netId of -1 when I try to add a network with addNetwork().
I'm tried the full blown config and a minimal config of :
```
var config = {
	  SSID: 'mySSID',
	  preSharedKey: 'wifiPassword'

	}
```
Do you maybe have a snippet on how to connect to to a wifi network using the ssid and password for the network? This seems to work with native examples likes [this one ](https://medium.com/@josiassena/android-manipulating-wifi-using-the-wifimanager-9af77cb04c6a)but doing the same with the plugin does not seem to work.

**Comment by kapetan** [comment]
You need to quote the `SSID` and `preSharedKey` like it's done in the article. E.g.

```js
var config = {
  SSID: '"mySSID"',
  preSharedKey: '"wifiPassword"'
}
```
Note quotes (") around the values.

**Comment by timonsku** [comment]
I did indeed miss those, adding the quotes did the trick, thank you!

**Comment by mm108** [comment]
> You need to quote the `SSID` and `preSharedKey` like it's done in the article. E.g.
> 
> ```js
> var config = {
>   SSID: '"mySSID"',
>   preSharedKey: '"wifiPassword"'
> }
> ```
> 
> Note quotes (") around the values.

Thanks for the useful plugin but just a quick question - from where are the other (default) values picked if I only pass the `SSID` and `preSharedKey`?

Would it be safe to assume that just passing `SSID` and `preSharedKey` is enough in most cases? Cheers

**Comment by kapetan** [comment]
This plugin does not add any additional default values. It just passes the provided values to underlying android wifi manager.

**Comment by mm108** [comment]
Okay thanks.
