### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by bbending626** [kapetan/cordova-plugin-android-wifi-manager#6]
@kapetan - I would like to use your plugin in our app. I don't see a LICENSE file in the repro and would like to know how I may use the plugin. Can you add a LICENSE file? Thank you. @bbending626

**Comment by kapetan** [comment]
Thanks for the feedback, I've now added the license file.

**Comment by bbending626** [comment]
Thank you.  I'll let you know when we release the app so you can see how your work is being used.

**Comment by kapetan** [comment]
Cool, let me know
