### ISSUE TITLE
Weird results

### ISSUE THREAD

**Issue by sealover06** [kapetan/cordova-plugin-android-wifi-manager#9]
hello team, 

on a simple test, WIFI connection, SSID not hidden, in Android 8.1, I get :  

wifiInfo.BSSID: 02:00:00:00:00:00 
wifiInfo.frequency; 2412
wifiInfo.hiddenSSID: true
wifiInfo.ipAddress: -50222912
wifiInfo.linkSpeed: 72
wifiInfo.macAddress: 02:00:00:00:00:00
wifiInfo.networkId: 0
wifiInfo.rssi: -39
wifiInfo.SSID: <unknown ssid>
wifiInfo.supplicantState: COMPLETED

my code : 
var WifiManager = cordova.plugins.WifiManager;

	WifiManager.getConnectionInfo(function (err, wifiInfo) {
		
		console.log( 'wifiInfo.BSSID: ' + wifiInfo.BSSID);
		console.log( 'wifiInfo.frequency; ' + wifiInfo.frequency);
		console.log( 'wifiInfo.hiddenSSID: ' + wifiInfo.hiddenSSID) ;
		console.log( 'wifiInfo.ipAddress: ' + wifiInfo.ipAddress);
		console.log( 'wifiInfo.linkSpeed: ' + wifiInfo.linkSpeed);
		console.log( 'wifiInfo.macAddress: ' + wifiInfo.macAddress);
		console.log( 'wifiInfo.networkId: ' + wifiInfo.networkId);
		console.log( 'wifiInfo.rssi: ' + wifiInfo.rssi);
		console.log( 'wifiInfo.SSID: ' + wifiInfo.SSID);
		console.log( 'wifiInfo.supplicantState: ' + wifiInfo.supplicantState );	
	});

Anything wrong with my code ? 
Thanks. 
Best Regards,

**Comment by kapetan** [comment]
No I haven't seen anything like that before. Hope you found you answer.
